#!/bin/bash
chmod 777 -R .
centos-base/build.sh
centos-gcc620/build.sh
template-gcc/build.sh
amunmt/build.sh
fr-kafka-producer/build.sh
tensorflow-ds-gcc/build.sh
deepspeech-inference/build.sh
deepspeech-training/build.sh
tensorflow-gcc/build.sh
cnn-flower-workload/build.sh
cnn-inference/build.sh
cnn-training/build.sh
fr-batch-flow/build.sh
fr-batch-training/build.sh
fr-spark-consumer/build.sh
fr-warmed-tensorflow/build.sh
threedmapping/build.sh
db-server/build.sh
discovery-service/build.sh
perf/build.sh
simple-queue-server/build.sh